# Generated by Django 3.0.7 on 2021-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
