# Generated by Django 3.0.7 on 2021-03-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_library_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('card_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('balance', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Library Cards',
                'ordering': ('name',),
            },
        ),
    ]
