# Generated by Django 3.0.7 on 2021-04-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('No Books - Confirmation', 'No_Books_Available_Confirmation'), ('Some Books - Confirmation', 'Some_Books_Available_Confirmation'), ('All Books - Confirmation', 'All_Books_Available_Confirmation'), ('Order Delivered', 'Order_Delivered'), ('Two Day Reminder', 'Two_Day_Reminder'), ('Due Today Reminder', 'Due_Today_Reminder'), ('Late Reminder', 'Late_Reminder'), ('Surpassed Late Limit', 'Surpassed_Late_Limit'), ('Books Picked Up', 'Books_Picked_Up'), ('Return Confirmation', 'Return_Confirmation')], max_length=50)),
                ('email_subject', models.CharField(blank=True, default='', max_length=255)),
                ('email_body', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Automated Messages',
            },
        ),
    ]
