# Generated by Django 3.0.7 on 2021-04-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210402_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
