# Generated by Django 3.0.7 on 2021-03-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alt_id', models.CharField(max_length=50)),
                ('slack_id', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='slack.SlackAccount')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alt_id', models.CharField(max_length=50)),
                ('bot_name', models.CharField(default='Channel Automator', max_length=50)),
                ('bot_image', models.TextField(blank=True, default='https://heliumbooks-webapp.s3.us-east-2.amazonaws.com/helium+primary+logo+(blue).png')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='slack.SlackAccount')),
            ],
            options={
                'verbose_name_plural': 'Channels',
                'ordering': ('name',),
            },
        ),
    ]
