# Generated by Django 3.0.7 on 2021-02-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeclient',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
