# Generated by Django 3.0.7 on 2021-02-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0003_stripecustomer_stripeinvoice_stripeinvoiceitem_stripeproduct_stripesetupintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesetupintent',
            name='stripe_client_secret',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
