# Generated by Django 3.0.7 on 2021-02-05 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'States',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timezone', models.CharField(choices=[('America/New_York', 'Eastern'), ('America/Chicago', 'Central'), ('America/Los_Angeles', 'Pacific')], max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.State')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField(blank=True, default='', null=True)),
                ('additional_street_address', models.TextField(blank=True, default='', null=True)),
                ('zip_code', models.CharField(max_length=12)),
                ('type', models.CharField(choices=[('Library', 'Library'), ('Delivery', 'Delivery'), ('Pick Up', 'Pick_Up')], max_length=50)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.City')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
