# Generated by Django 3.0.7 on 2021-01-30 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_placed', models.DateTimeField(blank=True, null=True)),
                ('drop_off_time', models.DateTimeField(blank=True, null=True)),
                ('drop_off_location', models.TextField(blank=True, default='', null=True)),
                ('pick_up_deadline', models.DateTimeField(blank=True, null=True)),
                ('library_pick_up_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('return_pick_up_time', models.DateTimeField(blank=True, null=True)),
                ('returned_time', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
                ('delivery_driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_driver', to=settings.AUTH_USER_MODEL)),
                ('pick_up_driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pick_up_driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Order Placed', 'Placed'), ('Awaiting Library Pick Up', 'Awaiting_Library_Pick_Up'), ('Awaiting Delivery', 'Awaiting_Delivery'), ('Awaiting Customer Pick Up', 'Awaiting_Customer_Pick_Up'), ('Awaiting Library Return', 'Awaiting_Library_Return'), ('Completed', 'Completed'), ('Denied', 'Denied'), ('Overdue', 'Overdue'), ('Lost', 'Lost')], default='', max_length=100, null=True)),
                ('order_placed', models.DateTimeField(blank=True, null=True)),
                ('pick_up_deadline', models.DateTimeField(blank=True, null=True)),
                ('library_pick_up_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('return_pick_up_time', models.DateTimeField(blank=True, null=True)),
                ('returned_time', models.DateTimeField(blank=True, null=True)),
                ('pick_up_location', models.TextField(blank=True, default='', null=True)),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books.Book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order')),
            ],
            options={
                'verbose_name_plural': 'Book Orders',
            },
        ),
    ]
