# Generated by Django 3.0.7 on 2021-01-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_by_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_initiated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Incomplete', 'Incomplete'), ('Order Placed', 'Placed'), ('Awaiting Library Pick Up', 'Awaiting_Library_Pick_Up'), ('Awaiting Delivery', 'Awaiting_Delivery'), ('Awaiting Customer Pick Up', 'Awaiting_Customer_Pick_Up'), ('Awaiting Library Return', 'Awaiting_Library_Return'), ('Completed', 'Completed'), ('Denied', 'Denied'), ('Overdue', 'Overdue'), ('Lost', 'Lost')], default='', max_length=100, null=True),
        ),
    ]
