# Generated by Django 3.0.7 on 2021-02-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_address_customer'),
        ('orders', '0002_auto_20210204_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drop_off_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.Address'),
        ),
    ]
