# Generated by Django 3.0.7 on 2021-02-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_drop_off_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookorder',
            old_name='pick_up_deadline',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='order',
            name='drop_off_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_information_submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
