# Generated by Django 3.0.7 on 2021-02-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210205_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Incomplete', 'Incomplete'), ('Order Placed', 'Placed'), ('Awaiting Library Assignment', 'Awaiting_Library_Assignment'), ('Awaiting Library Pick Up', 'Awaiting_Library_Pick_Up'), ('Awaiting Delivery', 'Awaiting_Delivery'), ('Awaiting Customer Pick Up', 'Awaiting_Customer_Pick_Up'), ('Awaiting Library Return', 'Awaiting_Library_Return'), ('Completed', 'Completed'), ('Denied', 'Denied'), ('Overdue', 'Overdue'), ('Lost', 'Lost')], default='', max_length=100, null=True),
        ),
    ]
