# Generated by Django 3.0.7 on 2021-02-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210224_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
