# Generated by Django 3.0.7 on 2021-03-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210225_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Placed', 'Placed'), ('Confirmed', 'Confirmed'), ('Picked Up From Library', 'Picked_Up_Library'), ('Delivered to Customer', 'Delivered_Customer'), ('Picked Up From Customer', 'Picked_Up_Customer'), ('Complete', 'Complete')], default='', max_length=100, null=True),
        ),
    ]
