# Generated by Django 3.0.7 on 2021-03-06 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_address_customer'),
        ('orders', '0010_auto_20210302_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pick_up_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pick_up_address', to='locations.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drop_off_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drop_off_address', to='locations.Address'),
        ),
    ]
