# Generated by Django 3.0.7 on 2021-03-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210306_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Incomplete', 'Incomplete'), ('Order Placed', 'Placed'), ('Awaiting Library Assignment', 'Awaiting_Library_Assignment'), ('Awaiting Library Pick Up', 'Awaiting_Library_Pick_Up'), ('Awaiting Delivery', 'Awaiting_Delivery'), ('Awaiting Customer Pick Up', 'Awaiting_Customer_Pick_Up'), ('Awaiting Library Return', 'Awaiting_Library_Return'), ('Renewal Requested', 'Renewal_Requested'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Denied', 'Denied'), ('Overdue', 'Overdue'), ('Lost', 'Lost')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Placed', 'Placed'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Picked Up From Library', 'Picked_Up_Library'), ('Delivered to Customer', 'Delivered_Customer'), ('Picked Up From Customer', 'Picked_Up_Customer'), ('Complete', 'Complete')], default='', max_length=100, null=True),
        ),
    ]
