# Generated by Django 3.0.7 on 2021-02-05 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('information', models.TextField(blank=True, default='', null=True)),
                ('orders', models.IntegerField(default=0)),
                ('cost', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Authors',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('genre', models.CharField(blank=True, choices=[('Horror', 'Horror'), ('Science Fiction', 'Science_Fiction'), ('Non Fiction', 'Non_Fiction')], default='', max_length=50, null=True)),
                ('pages', models.IntegerField(default=0)),
                ('requests', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books.Author')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ('title',),
            },
        ),
    ]
