# Generated by Django 3.0.7 on 2022-02-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220214_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', null=True)),
                ('books_in_subject', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='processed_from_open_lib',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='IsbnNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.TextField(blank=True, default='', null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books.Book')),
            ],
            options={
                'verbose_name_plural': 'Isbn Numbers',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(to='books.Subject'),
        ),
    ]
