# Generated by Django 3.0.7 on 2022-02-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220221_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_ol_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
